name: Android CI
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - uses: android-actions/setup-android@v3
        with:
          cmdline-tools-version: latest

      - name: Install SDK packages
        run: |
          sdkmanager "platform-tools" "platforms;android-34" "build-tools;34.0.0"

      - uses: gradle/gradle-build-action@v3

      - name: Build & Lint & Unit tests
        run: |
          chmod +x gradlew
          ./gradlew assembleDebug lintDebug testDebug --no-daemon
